site_name: ChatReviver Documentation
repo_url: https://github.com/ChatReviver/ChatReviver-Docs
edit_uri: edit/main/docs/

theme:
  name: material

  favicon: /images/logo.png
  logo: /images/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

    - search
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Light mode
    - light blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - toc:
      permalink: "#"

plugins:
  - git-revision-date-localized:
      type: timeago

nav:
  - Home:
      - Intoduction: index.md
      - Feature list: home/features.md
      - How to invite the bot: home/inviting_the_bot.md
      - FAQ: home/faq.md

  - Custom Prefixes: custom_prefixes.md

  - Reviver Commands:
      - Would you rather: reviver_commands/wyr.md
