name: Build with mkdocs and deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        run: python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: python3 -m mkdocs build

      - name: Deploy site
        run: |
          echo ${{ secrets.DEPLOY_SSH_KEY }} > ~/.ssh/id_rsa
          sftp -i ~/.ssh/id_rsa -P ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOSTNAME }}
          put ./site/* ${{ secrets.DEPLOY_PATH }}
          exit