name: Build with mkdocs and deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        run: python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin

      - uses: actions/checkout@v2

      - name: Build
        run: python3 -m mkdocs build

      - name: Deploy site
        uses: SamKirkland/web-deploy@1.0.0
        with:
          target-server: ${{ secrets.DEPLOY_HOSTNAME }}:${{ secrets.DEPLOY_PORT }}
          remote-user: ${{ secrets.DEPLOY_USER }}
          remote-key: ${{ secrets.DEPLOY_KEY }}
          source-path: ./site/
          desstination-path: ${{ secrets.DEPLOY_PATH }}
