name: Build with mkdocs and deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        run: python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: python3 -m mkdocs build

      - run: whereis ssh

      - name: Deploy site
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.DEPLOY_HOSTNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
          local_path: ./site/*
          remote_path: ${{ secrets.DEPLOY_PATH }}