name: Build with mkdocs and deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        run: python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: python3 -m mkdocs build


      - name: Set up SSL certificates
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} -H "${{ secrets.DEPLOY_HOSTNAME }}" > ~/.ssh/known_hosts

      - name: SFTP & upload
        shell: bash
        run: |
          sftp -i ~/.ssh/id_rsa -P ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOSTNAME }} <<EOF
          put -r ./site/* ${{ secrets.DEPLOY_PATH }}
          exit


      - name: Start SSH via Ngrok on failure
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.NGROK_PASSWORD }}

      - name: Sleep on failure
        if: ${{ failure() }}
        run: sleep 1h

