name: Build mkdocs and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SFTP_PUBLIC_KEY }}
      HOST: ${{ secrets.SFTP_HOSTNAME }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install deps
        run: python3 -m pip install mkdocs-material mkdocs-macros-plugin mkdocs-git-revision-date-localized-plugin

      - uses: actions/checkout@v2

      - name: Build
        run: python3 -m mkdocs build

      - name: Prepare SSH keys
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/deploy.pub
          sudo chmod 600 ~/.ssh/deploy
          sudo chmod 600 ~/.ssh/deploy.pub
          ssh-keyscan -H "$HOST" > ~/.ssh/known_hosts

      - name: Deploy to VPS
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: sftp://${{ secrets.SFTP_HOSTNAME }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          git-ftp-args: --key "~/.ssh/deploy" --pubkey "~/.ssh/deploy.pub"
          local-dir: ./site/
          server_dir: ${{ secrets.SFTP_DEPLOY_PATH }}
