name: Deploy to VPS

on:
  push:
    branches:
      - gh_pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SFTP_PUBLIC_KEY }}
      HOST: ${{ secrets.SFTP_HOSTNAME }}

    steps:
    - name: Pull latest build
      uses: actions/checkout@v2

    - name: Prepare SSH keys
      shell: bash
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/deploy.pub
        sudo chmod 600 ~/.ssh/deploy
        sudo chmod 600 ~/.ssh/deploy.pub
        ssh-keyscan -H "$HOST" > ~/.ssh/known_hosts

    - name: Deploy to VPS
      uses: SamKirkland/FTP-Deploy-Action@4
      with:
        server: sftp://${{ secrets.SFTP_HOSTNAME }}
        username: ${{ secrets.SFTP_USERNAME }}
        port: ${{ secrets.SFTP_PORT }}
        git-ftp-args: --key "~/.ssh/deploy" --pubkey "~/.ssh/deploy.pub"
        server_dir: ${{ secrets.SFTP_DEPLOY_PATH }}
